apiVersion: batch/v1
kind: Job
metadata:
  name: hog-job-u64-lr0001
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: us-central1-docker.pkg.dev/weight2-459208/hog-repo/hog-classifier:v3
        command: ["python", "solution.py", "--mode", "train", "--feature_type", "hog", "--num_unit", "64", "--learning_rate", "0.001"]
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb-secret
              key: api-key
        resources:
          # limits:
            # nvidia.com/gpu: 1
      restartPolicy: Never
  backoffLimit: 2 